### ISSUE TITLE
Deploy Bruce-Bot-3000 on AWS

### ISSUE THREAD

**Issue by lprivette** [USGS-WiM/Bruce-Bot-3000#2]
See read me for instructions. Reach out to @KipSullivan with Questions.

**Comment by aaronstephenson** [comment]
We should also alter the index.js file a bit so that it uses an IAM role instead of an IAM user with access keys.

**Comment by HansVraga** [comment]
Update time it posts to 1130 Eastern to accommodate the West Coast folks

**Comment by ChadFanguy-usgs** [comment]
Added Slack Bot named Bruce-Bot-3000 as per instructions in readme, enabled it for bruce-bot-3000 channel, and enabled Incoming Webhooks on it.

**Comment by ChadFanguy-usgs** [comment]
@aaronstephenson when I logged into console, it reported I did not have permissions to mess with IAM role. I think I have access to create the Lambda function and Bucket for the remaining steps.

**Comment by aaronstephenson** [comment]
Did you configure MFA for that AWS subaccount?

**Comment by ChadFanguy-usgs** [comment]
@KipSullivan do you know of a way for the index.js file to refer to using an IAM role instead of the access and secret keys?

**Comment by KipSullivan** [comment]
Yeah I bet there's a way, let me look into it and I'll get back to you.
________________________________

**Comment by aaronstephenson** [comment]
I can give you an example. I'll put it in Slack.

**Comment by ChadFanguy-usgs** [comment]
In "main" aws: setup bucket, lambda function and tested.
Schedule set for 11:30am every weekday. If Monday correctly runs, will close the issue.

**Comment by ChadFanguy-usgs** [comment]
Bruce bot correctly posted so closing issue.
